In [1]:
from IPython.display import HTML, display

data = [['Numpy Type','C Type'],
        ['np.bool', 'bool'],
        ['np.byte','Signed Char'],
        ['np.ubyte','Unsigned Char'],
        ['np.short','short'],
        ['np.ushort','unsigned short'],
        ['np.intc','nt'],
        ['np.uintc','unsigned int'],['np.int_','long'],['np.uint','unsigned long'],['np.longlong','long long'],
        ['np.ulonglong','unsigned long long'],['np.half / np.float16','Half Precision Float'],
        ['np.single','float'],['np.double','double'],['np.longdouble','long double'],['np.csingle','float complex'],
        ['np.cdouble','double complex'],['np.clongdouble','long double complex']
        ]

display(HTML(
   '<table><tr>{}</tr></table>'.format(
       '</tr><tr>'.join(
           '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in data)
       )
))

In [2]:
import numpy as np

In [3]:
y = np.float16(1234567890.0987654321)
print(y)

inf


In [4]:
x = np.float32(1234567890.0987654321)
print(x)

1234568000.0


In [5]:
x = np.int_([1,2,4])
x

array([1, 2, 4])

In [6]:
x = np.arange(3, dtype=np.uint8)
x

array([0, 1, 2], dtype=uint8)

In [7]:
x = np.arange(2, 10, 2)
x

array([2, 4, 6, 8])

In [8]:
x = np.array([1, 2, 3], dtype='f')
x

array([1., 2., 3.], dtype=float32)

In [9]:
x = np.int8(34)
x

34