In [1]:
import numpy as np

In [4]:
b = np.arange(28)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [5]:
c = b.reshape(4,7)
c

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

## Trignometry functions

In [8]:
np.sin(b) #sin function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593])

In [9]:
np.cos(b) #cosine function

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
        0.99120281,  0.64691932, -0.29213881])

In [11]:
np.tan(b) #tan function

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
        2.23716094e+00, -1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
       -2.13489670e+00, -1.33526407e-01,  1.17875355e+00, -3.27370380e+00])

In [12]:
np.log(b) #logarithm function

C:\Users\v-bapr\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687])

In [13]:
np.exp(b) #Exponential 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11])

In [14]:
np.sqrt(b) #Sqaure root function

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242])

## numpy.amin() and numpy.amax()

### These functions return the minimum and the maximum from the elements in the given array along the specified axis.

In [23]:
c

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [20]:
np.amin(c)

0

In [21]:
np.amax(c)

27

In [22]:
np.amin(c,1)

array([ 0,  7, 14, 21])

In [24]:
np.amax(c,1)

array([ 6, 13, 20, 27])

In [25]:
np.amin(c,0)

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
np.amax(c,0)

array([21, 22, 23, 24, 25, 26, 27])

## numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

In [28]:
np.ptp(c)

27

In [29]:
np.ptp(c,1) # Columns maximum-minimum

array([6, 6, 6, 6])

In [30]:
np.ptp(c,0) # rows maximum-minimum

array([21, 21, 21, 21, 21, 21, 21])

### Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall

In [31]:
np.percentile(c,25)

6.75

In [32]:
np.percentile(c,25,1)

array([ 1.5,  8.5, 15.5, 22.5])

In [33]:
np.percentile(c,25,0)

array([ 5.25,  6.25,  7.25,  8.25,  9.25, 10.25, 11.25])

### Standard deviation is the square root of the average of squared deviations from mean

In [34]:
np.std(c)

8.077747210701755

### Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2)

In [35]:
np.var(c)

65.25